layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 4
  exclude:
    archived: false
    forks: true
    projects:
      - static

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: eddie-pease-a5482130/
  # mastodon: your_username
  medium: eddiepease1
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

blogs:
  - name: Three Crucial Lessons for Launching an AI Startup
    description: Because AI startups require subtly different strategies than Software-as-a-Service (SaaS) startups
    web_url: https://medium.com/swlh/three-crucial-lessons-for-launching-an-ai-startup-976d1d44f370
    image_url: images/startup.jpg

  - name: Introducing Company2Vec
    description: Helping company analysis with machine learning
    web_url: https://towardsdatascience.com/introducing-company2vec-helping-company-analysis-with-machine-learning-c6790d7a6bf5
    image_url: images/vector.png

  - name: When shouldn't you use machine learning to make predictions?
    description: Machine Learning in a world of Radical Uncertainty
    web_url: https://towardsdatascience.com/when-shouldnt-you-use-machine-learning-to-make-predictions-61d25000ad88
    image_url: images/ml.jpg

  - name: Chess Ultralearning
    description: Best way to learn chess in under 100 hours
    web_url: https://medium.com/@eddiepease1/chess-ultralearning-best-way-to-learn-chess-in-under-100-hours-bf58abce6569
    image_url: images/chess.jpg

  - name: Why everyone should take Bitcoin seriously
    description: It is just too big an idea to ignore
    web_url: https://medium.com/datadriveninvestor/why-everyone-should-take-bitcoin-seriously-e11ec2bb86da
    image_url: images/bitcoin.jpg

  - name: How Meditation Works in Your Brain
    description: The connection between attention, awareness, and emotion
    web_url: https://elemental.medium.com/how-meditation-works-in-your-brain-86cadaff41eb
    image_url: images/meditation.jpg

  - name: How to speed up local machine learning model development
    description: Introducing an robust machine learning template
    web_url: https://towardsdatascience.com/how-to-speed-up-local-machine-learning-model-development-33df177893ec
    image_url: images/ml_2.png


topics:
  - name: Chess
    web_url: https://www.chess.com/member/eddiepease
    image_url: images/chess.jpg

  - name: Meditation
    image_url: images/meditation.jpg

  - name: Bitcoin
    image_url: images/bitcoin.jpg

  - name: Investing
    image_url: images/investing.jpg
