layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 4
  exclude:
    archived: false
    forks: true
    projects:
      - static

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: eddie-pease-a5482130/
  # mastodon: your_username
  medium: eddiepease1
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

blogs:
  - name: Chess Ultralearning
    description: Best way to learn chess in under 100 hours
    web_url: https://medium.com/@eddiepease1/chess-ultralearning-best-way-to-learn-chess-in-under-100-hours-bf58abce6569
    image_url: images/chess.jpg

  - name: Introducing Company2Vec
    description: Helping company analysis with machine learning
    web_url: https://towardsdatascience.com/introducing-company2vec-helping-company-analysis-with-machine-learning-c6790d7a6bf5
    image_url: images/vector.png

  - name: When shouldn't you use machine learning to make predictions?
    description: Machine Learning in a world of Radical Uncertainty
    web_url: https://towardsdatascience.com/when-shouldnt-you-use-machine-learning-to-make-predictions-61d25000ad88
    image_url: images/ml.jpg


topics:
  - name: Chess
    web_url: https://www.chess.com/member/eddiepease
    image_url: images/chess.jpg

  - name: Meditation
    image_url: images/meditation.jpg

  - name: Investing
    image_url: images/investing.jpg
